# 
# Appveyor build 
#
# @author Natesh Narain <nnaraindev@gmail.com>

os: Visual Studio 2015

clone_folder: c:\projects\gameboy

environment:
  GTEST_ROOT: c:\libs\googletest
  SFML_ROOT: c:\libs\sfml

install:
  - echo "Installing Google Test"
  - git clone --depth=1 https://github.com/google/googletest.git c:\tmp\googletest
  - cd c:\tmp\googletest
  - mkdir build && cd build
  - cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\libs\googletest
  - msbuild googletest-distribution.sln /verbosity:quiet
  - msbuild INSTALL.vcxproj /verbosity:quiet
  - set PATH=%PATH%;%GTEST_ROOT%\lib
  
  - echo "Installing SFML"
  - git clone https://github.com/SFML/SFML.git c:\tmp\sfml
  - cd c:\tmp\sfml && mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=c:\libs\sfml
  - msbuild SFML.sln /verbosity:quiet
  - msbuild INSTALL.vcxproj /verbosity:quiet
  - set PATH=%PATH%;%SFML_ROOT%

before_build:
  - cd c:\projects\gameboy
  - mkdir build && cd build
  - cmake -G "Visual Studio 14 2015" .. -DCMAKE_INSTALL_PREFIX=c:\projects\install

build:
  project: c:\projects\gameboy\build\gameboy.sln
  verbosity: minimal

after_build:
  - C:\projects\gameboy\build\tests\Debug\gameboy_tests.exe
  - C:\projects\gameboy\build\INSTALL.vcxproj
  - copy c:\libs\sfml\bin\* c:\gameboy
  - pwd
  - 7z a gameboy.zip -r c:\projects\install

artifacts:
- path: .\gameboy.zip
  name: gameboy
  
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: +F7/lKFe9fc9q4w0lCpc9tR1H4JucHiE7WuevfJCaWOeU/5ul8QojqNACB6ODFgT
  artifact: gameboy
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
  force_update: true 