# 
# Appveyor build 
#
# @author Natesh Narain <nnaraindev@gmail.com>

os: Visual Studio 2015

environment:
  CXXTEST_ROOT: c:\libs\cxxtest

clone_folder: c:\projects\gameboy

before_build:
  - echo "Install CxxTest..."
  - git clone https://github.com/CxxTest/cxxtest.git c:\libs\cxxtest
  - set INCLUDE=%INCLUDE%;%CXXTEST_ROOT%
  - echo "Generating Visual Studio Solution..."
  - cd c:\projects\gameboy
  - mkdir build && cd build
  - cmake -G "Visual Studio 14 2015" ..

build:
  project: c:\projects\gameboy\build\gameboy.sln
