#
# Appveyor build
#
# @author Natesh Narain <nnaraindev@gmail.com>

os: Visual Studio 2015

clone_folder: c:\projects\gameboycore

environment:
  GTEST_ROOT: c:\libs\googletest
  
configuration:
  - Release

install:
  - echo "Installing Google Test"
  - git clone --depth=1 https://github.com/google/googletest.git c:\tmp\googletest
  - cd c:\tmp\googletest
  - mkdir build && cd build
  - cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\libs\googletest
  - msbuild googletest-distribution.sln /verbosity:quiet
  - msbuild INSTALL.vcxproj /verbosity:quiet
  - set PATH=%PATH%;%GTEST_ROOT%\lib

before_build:
  - cd c:\projects\gameboycore
  - mkdir build && cd build
  - cmake .. -DBUILD_EXAMPLE="OFF" -DBUILD_DOCS="OFF"

build:
  msbuild c:\projects\gameboycore\build\gameboycore.sln
  verbosity: minimal

after_build:
  - C:\projects\gameboycore\build\tests\Release\gameboy_tests.exe
  - msbuild C:\projects\gameboycore\build\PACKAGE.vcxproj /verbosity:quiet

artifacts:
- path: .\build\gameboycore-*-win32.zip
  name: zip-file

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: +F7/lKFe9fc9q4w0lCpc9tR1H4JucHiE7WuevfJCaWOeU/5ul8QojqNACB6ODFgT
  artifact: zip-file
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
  force_update: true
