# 
# Appveyor build 
#
# @author Natesh Narain <nnaraindev@gmail.com>

os: Visual Studio 2015

environment:
  CXXTEST_ROOT: c:\libs\cxxtest
  
  matrix:

    # Python 2.7.10 is the latest version and is not pre-installed.

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"  

clone_folder: c:\projects\gameboy

install:
  - echo "Setting up Python"
  - set PATH=%PATH%;%PYTHON%
  - echo "Installing CxxTest..."
  - git clone --depth=1 https://github.com/CxxTest/cxxtest.git c:\libs\cxxtest
  - set INCLUDE=%INCLUDE%;%CXXTEST_ROOT%

before_build:
  - dir C:\
  - echo "Generating Visual Studio Solution..."
  - cd c:\projects\gameboy
  - mkdir build && cd build
  - cmake -G "Visual Studio 14 2015" ..

build:
  project: c:\projects\gameboy\build\gameboy.sln
